### ISSUE TITLE
Unable to use provided COMEDIAN checkpoint for inference

### ISSUE THREAD

**Issue by rtxbae** [juliendenize/eztorch#1]
Hello! Firstly thanks for providing this amazing library and research! I got an issue during the inference using the provided checkpoint.

I was unable to use the [ViViT Tiny checkpoint](https://juliendenize.github.io/eztorch/contributions/comedian.html#main-results) to run the inference. There are several missing keys in the checkpoint, such as `pytorch-lightning_version`, `global_step`, `epoch` and `state_dict`. However I modified them and artificially created the missing keys, and moved the whole checkpoint dict into the `state_dict`. Now I was greeted with another missing keys of the model itself:

```
RuntimeError: Error(s) in loading state_dict for SoccerNetSpottingModel:
        Missing key(s) in state_dict: "train_transform.0._transform.0.transforms.2.brightness", "train_transform.0._transform.0.transforms.2.contrast", "train_transform.0._transform.0.transforms.2.saturation", "val_transform.1._transform.0.transforms.2.mean", "val_transform.1._transform.0.transforms.2.std", "test_transform.1._transform.0.transforms.2.mean", "test_transform.1._transform.0.transforms.2.std".
        Unexpected key(s) in state_dict: "trunk.transformer.temporal_mask_token", "val_transform.1._transform.2.mean", "val_transform.1._transform.2.std", "test_transform.1._transform.2.mean", "test_transform.1._transform.2.std".
        size mismatch for train_transform.0._transform.0.transforms.5.mean: copying a param with shape torch.Size([3]) from checkpoint, the shape in current model is torch.Size([3, 1, 1]).
        size mismatch for train_transform.0._transform.0.transforms.5.std: copying a param with shape torch.Size([3]) from checkpoint, the shape in current model is torch.Size([3, 1, 1]).
```
I'm using the [inference step args](https://juliendenize.github.io/eztorch/contributions/comedian.html#inference) in the doc, with this as the inference input config
```
config_path="../eztorch/configs/run/finetuning/vivit"
config_name="vivit_tiny_soccernet_uniform"
...
```

Do you have any idea what did I miss?

Thanks again!

**Comment by juliendenize** [comment]
Hello @rtxbae, thanks for finding our work useful!

Sorry, I cleaned the checkpoints to make them lighter and did not think about how it would impact lightning. I updated the code and the related command lines for inference. Could you confirm it works for you?

**Comment by rtxbae** [comment]
Thanks for the speedy fix @juliendenize, appreciate them very much. Now they ran as expected!

However, I think there's another specifically at this line where `class_preds` is not defined locally.
https://github.com/juliendenize/eztorch/blob/52651b4c781b65c7c716d9f08f61ad805bb22722/eztorch/models/soccernet_spotting.py#L467

Seemingly they're missing the same line in validation step?
https://github.com/juliendenize/eztorch/blob/7fe29ae714990b1b743f72142a04a87f447e3168/eztorch/models/soccernet_spotting.py#L391

**Comment by juliendenize** [comment]
Hello again @rtxbae, indeed apparently I removed one critical line while cleaning the code. I made the fix and ran the code it should be working now and I obtained `70.5` t-map with this checkpoint. 

To obtain the results from the paper, I just added the checkpoints for the two architectures for the three seeds. The ones initially provided are using seed 42. `70.7` should be the average result across the three seeds.

Could you confirm it works for you now?

**Comment by rtxbae** [comment]
Hey thanks again @juliendenize  for another fix! Now everything works as expected. Super awesome that you included few other checkpoints too, I was trying to reproduce the result from the paper 😁
